### ISSUE TITLE
State graphs with Graphviz

### ISSUE THREAD

**Issue by hengxin** [mryndzionek/tlaplus_specs#2]
Hi, it is a very nice job. I am wondering how did you generate the fancy state graphs, such as [this](https://github.com/mryndzionek/tlaplus_specs/blob/master/images/gameoflife_4x4c.png) and [this](https://github.com/mryndzionek/tlaplus_specs/blob/master/images/blinker.png)? I failed to reproduce them using the built-in Graphviz tool of TLC Toolbox. Thanks.

**Comment by mryndzionek** [comment]
Hello. Thanks for the kind words! In order to get those state graphs you need to:

1. post-process the dot files generated by TLC using your favorite language. I was using Haskell for this, but Python will also do. Dot is a simple format. Things like replacing node colors are easy to do.
2. run `dot` with some other options than TLC runs them by default. There is an example the in readme:
        ```
        dot -Tpng -Nstyle=filled -Npenwidth=5 -Epenwidth=8 -Ksfdp -Goverlap=prism -Goverlap_scaling=-10
        ```

**Comment by hengxin** [comment]
@mryndzionek It works! Very nice! Great thanks.
